# Generated by Django 4.0.6 on 2022-07-22 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('adresse', models.CharField(max_length=200)),
                ('CodePostal', models.IntegerField()),
                ('ville', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='option1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.BooleanField()),
                ('fournisseur', models.BooleanField()),
                ('banque', models.BooleanField()),
                ('chiffre', models.BooleanField()),
                ('assistance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='option2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kine', models.BooleanField(default=False)),
                ('Accompagne', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('planing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='option3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.BooleanField(default=False)),
                ('mailing', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('entretiens', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(choices=[('Paris', 'Paris'), ('Bordeaux', 'Bordeaux'), ('Nice', 'Nice'), ('Lille', 'Lille'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Brest', 'Brest'), ('Lyon', 'Lyon'), ('Strabourg', 'Strabourg'), ('Nantes', 'Nantes'), ('Toulouse', 'Toulouse'), ('Nîmes', 'Nîmes'), ('Rennes', 'Renne'), ('Angers', 'Angers'), ('Limoges', 'Limoges'), ('Tours', 'Tours')], default='Paris', max_length=15)),
                ('email', models.EmailField(default='Paris', max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('numberPhone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ville')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(default=0, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salle')),
                ('option', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], default='option 1', max_length=10)),
                ('numberPhone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('piscine', models.BooleanField(default=False)),
                ('haman', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.partenaire')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partenaire',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.structure'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='entreprise',
            field=models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.structure'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='partenaire',
            field=models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.partenaire'),
        ),
    ]
