# Generated by Django 4.0.6 on 2022-07-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('adresse', models.CharField(max_length=200)),
                ('abonnement', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], default='option 1', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
