# Generated by Django 4.0.6 on 2022-07-19 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('numeros', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('adresse', models.CharField(max_length=200)),
                ('CodePostal', models.IntegerField(default=0)),
                ('ville', models.CharField(default=0, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='option1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.BooleanField()),
                ('fournisseur', models.BooleanField()),
                ('banque', models.BooleanField()),
                ('chiffre', models.BooleanField()),
                ('assistance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='option2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kine', models.BooleanField(default=False)),
                ('Accompagne', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('planing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='option3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.BooleanField(default=False)),
                ('mailing', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('entretiens', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salle')),
                ('option', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], default='option 1', max_length=10)),
                ('numberPhone', models.IntegerField()),
                ('piscine', models.BooleanField(default=False)),
                ('haman', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(choices=[('1', 'Paris'), ('2', 'Bordeaux'), ('3', 'Nice'), ('4', 'Lille'), ('5', 'Marseille'), ('6', 'Montpellier'), ('7', 'Brest'), ('8', 'Lyon'), ('9', 'Strabourg'), ('10', 'Nantes')], default='Paris', max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('numberPhone', models.IntegerField()),
                ('numberThec', models.IntegerField()),
                ('salle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.structure')),
            ],
        ),
    ]
