# Generated by Django 4.0.6 on 2022-07-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user',
            new_name='username',
        ),
    ]
