# Generated by Django 4.0.6 on 2022-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='CodePostal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
