# Generated by Django 4.0.6 on 2022-08-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_is_staff'),
        ('accounts', '0002_alter_partenaire_resp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Groupe',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Groupe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
