# Generated by Django 4.0.6 on 2022-07-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='numeros',
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numberPhone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numberThec',
            field=models.IntegerField(max_length=20),
        ),
    ]
