# Generated by Django 4.0.6 on 2022-07-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_codepostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='structure',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.partenaire'),
        ),
    ]
