# Generated by Django 4.0.6 on 2022-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_numeros_alter_partenaire_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='numberPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numberThec',
            field=models.IntegerField(),
        ),
    ]
