# Generated by Django 4.0.6 on 2022-09-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_groupe_myuser_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
