# Generated by Django 4.0.6 on 2022-07-24 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_partenaire_email_alter_structure_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
