# Generated by Django 4.0.6 on 2022-09-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_is_staff'),
        ('accounts', '0004_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
