# Generated by Django 4.0.6 on 2022-07-19 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_partenaire_numberphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='entreprise',
            field=models.OneToOneField(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
