# Generated by Django 4.0.6 on 2022-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_structure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(choices=[('paris', 'paris'), ('Bordeaux', 'bordeaux'), ('Nice', 'nice'), ('Lille', 'lille'), ('Marseille', 'marseille'), ('Montpellier', 'montpellier'), ('Brest', 'brest'), ('Lyon', 'lyon'), ('Strabourg', 'strabourg'), ('Nantes', 'nantes'), ('Toulouse', 'toulouse'), ('Nîmes', 'nîmes'), ('Rennes', 'renne'), ('Angers', 'angers'), ('Limoges', 'limoges'), ('Tours', 'tours')], default='Paris', max_length=15),
        ),
    ]
