# Generated by Django 4.0.6 on 2022-07-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_entreprise_alter_structure_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='partenaire',
            field=models.OneToOneField(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.partenaire'),
        ),
    ]
