# Generated by Django 4.0.6 on 2022-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_partenaire_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.BooleanField(default=False)),
                ('fournisseur', models.BooleanField(default=False)),
                ('banque', models.BooleanField(default=False)),
                ('chiffre', models.BooleanField(default=False)),
                ('assistance', models.BooleanField(default=False)),
                ('kine', models.BooleanField(default=False)),
                ('Accompagne', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('planing', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('mailing', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('entretiens', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='option1',
        ),
        migrations.DeleteModel(
            name='option2',
        ),
        migrations.DeleteModel(
            name='option3',
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Bordeaux', 'Bordeaux'), ('Nice', 'Nice'), ('Lille', 'Lille'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Brest', 'Brest'), ('Lyon', 'Lyon'), ('Strabourg', 'Strabourg'), ('Nantes', 'Nantes'), ('Toulouse', 'Toulouse'), ('Nîmes', 'Nîmes'), ('Rennes', 'Renne'), ('Angers', 'Angers'), ('Limoges', 'Limoges'), ('Tours', 'Tours')], default='Paris', max_length=15),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='option',
        ),
        migrations.AlterField(
            model_name='structure',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='structure',
            name='option',
            field=models.ManyToManyField(to='accounts.option'),
        ),
    ]
