# Generated by Django 4.0.6 on 2022-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_option_delete_option1_delete_option2_delete_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='option',
        ),
        migrations.AddField(
            model_name='structure',
            name='Accompagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='bail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='banque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='chiffre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='entretiens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='fournisseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='kine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='planing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='structure',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='option',
        ),
    ]
