# Generated by Django 4.0.6 on 2022-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Bordeaux', 'Bordeaux'), ('Nice', 'Nice'), ('Lille', 'Lille'), ('Marsielle', 'Marseille'), ('Montpellier', 'Montpellier'), ('Brest', 'Brest'), ('Lyon', 'Lyon'), ('Strabourg', 'Strabourg'), ('Nantes', 'Nantes')], default='Paris', max_length=15),
        ),
    ]
