# Generated by Django 4.0.6 on 2022-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_partenaire_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='numberPhone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
