# Generated by Django 4.0.6 on 2022-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_structure_option_structure_accompagne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
