# Generated by Django 4.0.6 on 2022-09-02 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_partenaire_numberphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='numberPhone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='structure',
            name='numberPhone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
