# Generated by Django 4.0.6 on 2022-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_partenaire_actif_structure_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='description',
            field=models.CharField(max_length=70),
        ),
    ]
