# Generated by Django 4.0.6 on 2022-09-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_partenaire_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Groupe',
        ),
        migrations.AddField(
            model_name='myuser',
            name='entreprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.structure'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.partenaire'),
        ),
    ]
