# Generated by Django 4.0.6 on 2022-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_partenaire_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Bordeaux', 'Bordeaux'), ('Nice', 'Nice'), ('Lille', 'Lille'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Brest', 'Brest'), ('Lyon', 'Lyon'), ('Strasbourg', 'Strasbourg'), ('Nantes', 'Nantes'), ('Toulouse', 'Toulouse'), ('Nîmes', 'Nîmes'), ('Rennes', 'Renne'), ('Angers', 'Angers'), ('Limoges', 'Limoges'), ('Tours', 'Tours')], default='Paris', max_length=15),
        ),
    ]
