# Generated by Django 4.0.6 on 2022-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_option_options_remove_myuser_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ville/'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='salle/'),
        ),
    ]
