# Generated by Django 4.0.6 on 2022-07-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_partenaire_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='slug',
        ),
    ]
