# Generated by Django 4.0.6 on 2022-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_partenaire_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='membre',
            field=models.IntegerField(default=0),
        ),
    ]
