# Generated by Django 4.0.6 on 2022-07-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_structure_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='slug',
        ),
    ]
