# Generated by Django 4.0.6 on 2022-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_myuser_photo_alter_partenaire_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ville/'),
        ),
    ]
