# Generated by Django 4.0.6 on 2022-08-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_is_staff'),
        ('accounts', '0015_remove_myuser_slug_structure_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bail', models.BooleanField(default=False)),
                ('fournisseur', models.BooleanField(default=False)),
                ('banque', models.BooleanField(default=False)),
                ('chiffre', models.BooleanField(default=False)),
                ('assistance', models.BooleanField(default=False)),
                ('kine', models.BooleanField(default=False)),
                ('Accompagne', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('planing', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('mailing', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('entretiens', models.BooleanField(default=False)),
                ('membre', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='structure',
            name='Accompagne',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='assistance',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='bail',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='chiffre',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='entretiens',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='kine',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='member',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='planing',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='promotion',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Groupe',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='option',
            field=models.ManyToManyField(to='accounts.option'),
        ),
        migrations.AddField(
            model_name='structure',
            name='option',
            field=models.ManyToManyField(to='accounts.option'),
        ),
    ]
