# Generated by Django 4.0.6 on 2022-08-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_option_remove_structure_accompagne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_permission',
        ),
    ]
