# Generated by Django 4.0.6 on 2022-08-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_myuser_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='membre',
        ),
        migrations.AddField(
            model_name='structure',
            name='membre',
            field=models.IntegerField(default=0),
        ),
    ]
