# Generated by Django 4.0.6 on 2022-08-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_option_membre_structure_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='Accompagne',
        ),
        migrations.RemoveField(
            model_name='option',
            name='assistance',
        ),
        migrations.RemoveField(
            model_name='option',
            name='bail',
        ),
        migrations.RemoveField(
            model_name='option',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='option',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='option',
            name='chiffre',
        ),
        migrations.RemoveField(
            model_name='option',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='option',
            name='entretiens',
        ),
        migrations.RemoveField(
            model_name='option',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='option',
            name='kine',
        ),
        migrations.RemoveField(
            model_name='option',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='option',
            name='member',
        ),
        migrations.RemoveField(
            model_name='option',
            name='piscine',
        ),
        migrations.RemoveField(
            model_name='option',
            name='planing',
        ),
        migrations.RemoveField(
            model_name='option',
            name='promotion',
        ),
        migrations.AddField(
            model_name='option',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
