# Generated by Django 4.0.6 on 2022-08-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_description_option_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='slug',
        ),
    ]
