# Generated by Django 4.0.6 on 2022-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_description_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='description',
        ),
    ]
