# Generated by Django 4.0.6 on 2022-08-01 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_option_description_delete_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='partenaire',
            new_name='parten',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
