# Generated by Django 4.0.6 on 2022-08-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_partenaire_myuser_parten_partenaire_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
