# Generated by Django 4.0.6 on 2022-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_partenaire_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='parten',
            new_name='partenaire',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='option',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='username',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='option',
        ),
        migrations.AddField(
            model_name='structure',
            name='Accompagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='bail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='chiffre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='entrentiens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='fournisseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='kine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='planing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='regim',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='option',
        ),
    ]
