# Generated by Django 4.0.6 on 2022-08-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_parten_myuser_partenaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='chiffre',
            new_name='banque',
        ),
    ]
