# Generated by Django 4.0.6 on 2022-08-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_chiffre_structure_banque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='bail',
            new_name='bails',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='entrentiens',
            new_name='entretiens',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='fournisseur',
            new_name='fourni',
        ),
    ]
