# Generated by Django 4.0.6 on 2022-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_bail_structure_bails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='chiffre',
            field=models.BooleanField(default=False),
        ),
    ]
