# Generated by Django 4.0.6 on 2022-08-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_structure_chiffre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='chiffre',
            new_name='chiffres',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='regim',
        ),
    ]
